version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run Test1.py
          command: python Python/Test1.py
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: List files for debugging
          command: ls -R
      - run:
          name: Run Test2.py
          command: python Python/Test2.py
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Run Deploying
          command: echo "Deployed in the environment"

workflows:
  build_now:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
            
